# Generated by Django 5.1.2 on 2024-11-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="check_in",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="check_out",
            field=models.DateField(),
        ),
    ]
