# Generated by Django 5.1.2 on 2024-11-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lists", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lists",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="lists", to="rooms.room"
            ),
        ),
    ]
